app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path:      /login/
    defaults:  { _controller: AppBundle:Connection:index }

hello:
    path:      /hello/
    defaults:  { _controller: AppBundle:Hello:index }