app:
    resource: "@AppBundle/Controller/"
    type:     annotation

connect:
    path:      /connect/
    defaults:  { _controller: AppBundle:Connection:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

homepage:
    path:      /
    defaults:  { _controller: AppBundle:Home:index }

hello:
    path:      /hello/
    defaults:  { _controller: AppBundle:Hello:index }

analyse:
    path:      /analyse
    defaults:  { _controller: AppBundle:Analyse:index }

analyse_create:
    path:      /analyse/create
    defaults:  { _controller: AppBundle:Analyse:create }

analyse_upload:
    path:      /analyse/upload
    defaults:  { _controller: AppBundle:Analyse:upload }

analyse_edit:
    path:      /analyse/edit/{analyseId}
    defaults:  { _controller: AppBundle:Analyse:edit }

analyse_addparam:
    path:      /analyse/{analyseId}/addParam
    defaults:  { _controller: AppBundle:Param:add }

analyse_dataserielist:
    path:      /analyse/{analyseId}/dataserielist
    defaults:  { _controller: AppBundle:Dataserie:list }

analyse_add_dataserie:
    path:      /analyse/{analyseId}/adddataserie
    defaults:  { _controller: AppBundle:Dataserie:add }

dataserie_delete:
    path:      /dataserie/{dataserieId}/delete
    defaults:  { _controller: AppBundle:Dataserie:delete }

param_delete:
    path:      /param/delete/{paramId}
    defaults:  { _controller: AppBundle:Param:delete }



