# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    analyse_service:
        class: AppBundle\Services\AnalyseService
        arguments: [ @doctrine.orm.entity_manager ]
    param_service:
        class: AppBundle\Services\ParamService
        arguments: [ @doctrine.orm.entity_manager ]
    datatable_service:
        class: AppBundle\Services\DatatableService
        arguments: [ @doctrine.orm.entity_manager ]
    param_form:
        class: AppBundle\Form\ParamType
    dataserie_form:
        class: AppBundle\Form\DataserieType
    value_form:
        class: AppBundle\Form\ValueType
