# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine

    # START ENTITIES SERVICES #
    analyse_service:
        class: AppBundle\Services\AnalyseService
        arguments: [ @doctrine.orm.entity_manager ]
    param_service:
        class: AppBundle\Services\ParamService
        arguments: [ @doctrine.orm.entity_manager ]
    dataserie_service:
        class: AppBundle\Services\DataserieService
        arguments: [ @doctrine.orm.entity_manager ]
    chart_service:
        class: AppBundle\Services\ChartService
        arguments: [ @doctrine.orm.entity_manager ]
    datatable_service:
        class: AppBundle\Services\DatatableService
        arguments: [ @doctrine.orm.entity_manager ]
    excel_service:
        class: AppBundle\Services\ExcelService
        arguments: [ @doctrine.orm.entity_manager, @phpexcel ]
    # END ENTITIES SERVICES #

    # START FORM SERVICES #
    analyse_form:
        class: AppBundle\Form\AnalyseType
    analyse1_form:
        class: AppBundle\Form\Analyse1Type
    param_form:
        class: AppBundle\Form\ParamType
    param1_form:
        class: AppBundle\Form\Param1Type
    dataserie_form:
        class: AppBundle\Form\DataserieType
    dataserie1_form:
        class: AppBundle\Form\Dataserie1Type
    value_form:
        class: AppBundle\Form\ValueType
    document_form:
        class: AppBundle\Form\DocumentType
    # END FORM SERVICES #