<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Param1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Param1Repository extends EntityRepository
{
    public function getParamsByAnalyseId($analyseId)
    {
        return $this->_em->getRepository('AppBundle:Param1')->findByAnalyse1($analyseId);
    }
}
