<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Param1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Param1Repository extends EntityRepository
{
}
