<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Value1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Value1Repository extends EntityRepository
{
}
